### ISSUE TITLE
hi，老哥想请教一下

### ISSUE THREAD

**Issue by zFengling** [F-Light/singlenet-#1]
我学校同样是**wenet**，采用的**portal**网页认证，想通过curl抓包获取，免输入账号密码登录
但抓包获取到的参数是 在**request payload**，其中有一项参数request url里涉及到usrma，
直接使用获取到curl，用错误的账号密码登录会反馈密码错误，使用正确的密码账号，反而没有反应
是否与老哥的portal认证方式类似，有解决办法吗

**Comment by F-Light** [comment]
认证方式不一样，暂时帮不了你
